name: Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Intel App
        run: |
          ARCH="x86_64" ./build.sh
          mv build/NeovideProject.app build/NeovideProject-intel.app
          mv build/NeovideProject.dmg build/NeovideProject-intel.dmg

      - name: Build ARM App
        run: |
          ARCH="arm64" ./build.sh
          mv build/NeovideProject.app build/NeovideProject-arm.app
          mv build/NeovideProject.dmg build/NeovideProject-arm.dmg

      - name: Create Universal App
        run: |
          mkdir -p build/NeovideProject.app/Contents/MacOS
          lipo -create \
            build/NeovideProject-intel.app/Contents/MacOS/neovide-project-launcher \
            build/NeovideProject-arm.app/Contents/MacOS/neovide-project-launcher \
            -output build/NeovideProject.app/Contents/MacOS/neovide-project-launcher
          cp -r build/NeovideProject-intel.app/Contents/{Info.plist,Resources} build/NeovideProject.app/Contents/

          # Create universal DMG
          hdiutil create -volname "NeovideProject" -srcfolder "build/NeovideProject.app" -ov -format UDZO "build/NeovideProject-universal.dmg"

      - name: Verify Build Artifacts
        run: |
          ls -la build/
          file build/NeovideProject-intel.app/Contents/MacOS/neovide-project-launcher
          file build/NeovideProject-arm.app/Contents/MacOS/neovide-project-launcher
          file build/NeovideProject.app/Contents/MacOS/neovide-project-launcher
          test -f "build/NeovideProject-intel.dmg"
          test -f "build/NeovideProject-arm.dmg"
          test -f "build/NeovideProject-universal.dmg"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/NeovideProject-intel.dmg
            build/NeovideProject-arm.dmg
            build/NeovideProject-universal.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

